name: Deploy FplTeamPicker Apps

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3      
      
      - name: Substitute appsettings.json variables
        uses: microsoft/variable-substitution@v1
        with:
          files: 'Api/FplTeamPicker.Api/appsettings.json'
        env:
          EndpointConfig.UiUrl: ${{ vars.UI_URL }}

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/src
          acrName: autofpl
          containerAppName: auto-fpl-api
          resourceGroup: auto-fpl
    

      # Build and Deploy Web
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Or your desired node version.

      - name: Install Web dependencies
        run: |
          cd Web/fpl-team-picker
          npm install

      - name: Build Web
        run: |
          cd Web/fpl-team-picker
          npm run build
        env:
          VITE_API_BASE_URL: ${{ vars.API_URL }} #example of passing an env variable.

      - name: Deploy Web to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: auto-fpl
          resource-group: auto-fpl
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_WEB }}
          package: Web/fpl-team-picker/dist

env:
  API_DEPLOY_PATH: './Api/deploy'